name: Build & Publish Prod
on:
  push:
    branches: [ 'main' ]
jobs:
  setup:
    name: Setup Build Parameters
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parameters.outputs.VERSION }}
      repo: harbor.ops.altronstudio.com/stable
      cache-repo: harbor.ops.altronstudio.com/build-cache
      cache-ttl: 168h
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Export Parameters
        id: parameters
        run: |
          echo "VERSION=$(git tag --sort=creatordate --merged | grep -oP '(\d+\.)?(\d+\.)?(\*|\d+)' | tail -1)" >> $GITHUB_OUTPUT
  build-front:
    name: Build Front API
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: https://harbor.ops.altronstudio.com
          username: ${{ secrets.HELM_REGISTRY_USER }}
          password: ${{ secrets.HELM_REGISTRY_PASSWORD }}
      - name: Build & Push
        uses: int128/kaniko-action@v1
        env:
          FRONTAPI_IMAGE: ${{ needs.setup.outputs.repo }}/demo/frontapi:${{ needs.setup.outputs.version }}
        with:
          context: apps/frontapi/
          file: .github/docker/front-api/Dockerfile
          tags: ${{ env.FRONTAPI_IMAGE }}
          push: true
          cache: true
          cache-repository: ${{ needs.setup.outputs.cache-repo }}/demo/frontapi
          cache-ttl: ${{ needs.setup.outputs.cache-ttl }}
  build-back:
    name: Build Brack API
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: https://harbor.ops.altronstudio.com
          username: ${{ secrets.HELM_REGISTRY_USER }}
          password: ${{ secrets.HELM_REGISTRY_PASSWORD }}
      - name: Build & Push
        uses: int128/kaniko-action@v1
        env:
          BACKAPI_IMAGE: ${{ needs.setup.outputs.repo }}/demo/backapi:${{ needs.setup.outputs.version }}
        with:
          context: apps/backapi/
          file: .github/docker/back-api/Dockerfile
          tags: ${{ env.BACKAPI_IMAGE }}
          push: true
          cache: true
          cache-repository: ${{ needs.setup.outputs.cache-repo }}/demo/backapi
          cache-ttl: ${{ needs.setup.outputs.cache-ttl }}
  build-helm:
    name: Build & Publish Chart
    runs-on: ubuntu-latest
    needs: [ setup, build-front, build-back ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Helm
        run: echo ${{ secrets.HELM_REGISTRY_PASSWORD }} | helm registry login harbor.ops.altronstudio.com -u ${{ secrets.HELM_REGISTRY_USER }} --password-stdin
      - name: Helm Package
        env:
          VERSION: ${{ needs.setup.outputs.version }}
        run: helm package ./.github/helm --version ${{ env.VERSION }} --app-version ${{ env.VERSION }}
      - name: Helm Push
        env:
          VERSION: ${{ needs.setup.outputs.version }}
        run: helm push ./demo-${{ env.VERSION }}.tgz oci://${{ needs.setup.outputs.repo }}
